### ISSUE TITLE
R table markdown issue

### ISSUE THREAD

**Issue by davidmdrake** [bradleyboehmke/learningAnalytics#1]
Tables don't show up and have to continuously refresh page, but it refreshes to top of training.
Try this:
In help tutorial, 
Change 
```{r}
mtcars
```
to:

```{r table, results='asis'}
library(pander)
pandoc.table(mtcars, style="rmarkdown")
```

**Comment by davidmdrake** [comment]
https://stackoverflow.com/questions/13224390/r-markdown-to-latex-tables-do-not-show-up
is the link with the solution

**Comment by bradleyboehmke** [comment]
@davidmdrake Sorry for the delayed response on this.  Although your code provides a local fix, I was hesitant because it correct the underlying issue (plus it incorporates unnecessary code that the learning doesn't need to see).  So I discussed this with the developers of the interactive capability that this R package is built on ([learnr](https://rstudio.github.io/learnr/)).  They found the problem and will have it fixed for their next push to CRAN.  You can see the discussion here: https://github.com/rstudio/learnr/issues/88.  Thanks!
